spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:dev
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
    time-zone: GMT-3
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
